// Server-only game outcome engine for WINZA's wheel/lotto bets. This is the
// ONLY place a bet's win/loss is decided — the client never sees or
// influences any of this; see /api/v1/games/bets in server.js and
// wallet.placeBet() in wallet.js, which call into here inside a single
// database transaction.
const crypto = require('node:crypto');
const { computeChance, computePayout } = require('./rtp-config');

// crypto.randomInt's documented range is [min, max) with (max - min)
// required to be no greater than 2^48 - 1 — using that full allowed range
// gives ~281 trillion discrete outcomes, far more resolution than any
// RTP/odds calculation here needs, and is generated by Node's CSPRNG (not
// Math.random(), which is not cryptographically secure and would let a
// sufficiently motivated player predict or bias outcomes).
const RANDOM_RESOLUTION = 2 ** 48 - 1;

function secureRandomDraw() {
  const randomInt = crypto.randomInt(0, RANDOM_RESOLUTION);
  return { randomInt, randomValue: randomInt / RANDOM_RESOLUTION };
}

// TEST MODE ONLY - REMOVE BEFORE PRODUCTION
// Lets a developer deterministically force every bet to win, for local
// end-to-end testing of balance updates, payout calculation, transaction
// history, and UI — without touching the real RTP/RNG decision logic above.
// Gated the same way OTP_DEV_ECHO is in server.js: requires BOTH an explicit
// per-deployment opt-in (WINZA_FORCE_WIN_DEV) AND WINZA_MODE !== 'live', so a
// stray env var left set on a real deployment still can't rig outcomes —
// WINZA_MODE stays 'sandbox' through the Play Store launch, same caveat as
// OTP_DEV_ECHO. Leave WINZA_FORCE_WIN_DEV unset everywhere except your own
// local machine.
const MODE = process.env.WINZA_MODE || 'sandbox';
const FORCE_WIN_TEST_MODE = MODE !== 'live' && process.env.WINZA_FORCE_WIN_DEV === 'true';

// A tamper-evident fingerprint over the exact draw that decided a bet,
// keyed with the server's own secret (never sent to the client). Lets staff
// verify after the fact that a stored random_value/result genuinely matches
// what the RNG produced for that bet, without exposing anything that would
// let a player predict future draws. Domain-separated from JWT signing via
// the fixed label, even though it reuses JWT_SECRET rather than requiring a
// second dedicated secret to configure.
function auditFingerprint(secret, betId, randomInt) {
  return crypto.createHmac('sha256', secret).update(`winza-bet-audit:${betId}:${randomInt}`).digest('hex');
}

// Resolves one bet: draws a cryptographically secure random value, applies
// the configured RTP (via the shared computeChance formula so this can never
// drift from what the client's pre-bet odds preview showed), and computes
// the payout if it's a win. Pure function — no I/O, no DB access — so it's
// trivially unit-testable and reused identically by wallet.placeBet().
function resolveBet({ stake, multiplier, rtp, auditSecret, betId }) {
  const chance = computeChance(rtp, multiplier);
  const { randomInt, randomValue } = secureRandomDraw();
  // TEST MODE ONLY - REMOVE BEFORE PRODUCTION
  // Only the win/loss decision is bypassed here; computePayout() below runs
  // exactly as it would for a real win, so payout math is still exercised.
  const win = FORCE_WIN_TEST_MODE ? true : randomValue < chance;
  const payout = win ? computePayout(stake, multiplier) : 0;
  return {
    chance,
    randomValue,
    result: win ? 'win' : 'loss',
    payout,
    auditFingerprint: auditFingerprint(auditSecret, betId, randomInt),
  };
}

module.exports = { resolveBet, secureRandomDraw, auditFingerprint, RANDOM_RESOLUTION, FORCE_WIN_TEST_MODE };
